// <auto-generated />
using System;
using LibraryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<DateTime?>("BirthDate").HasColumnType("TEXT");
                    b.Property<string>("Country").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Authors");
                    b.HasData(
                        new { Id = 1, BirthDate = new DateTime(1828, 9, 9), Country = "Россия", FirstName = "Лев", LastName = "Толстой" },
                        new { Id = 2, BirthDate = new DateTime(1821, 11, 11), Country = "Россия", FirstName = "Фёдор", LastName = "Достоевский" },
                        new { Id = 3, BirthDate = new DateTime(1891, 5, 15), Country = "Россия", FirstName = "Михаил", LastName = "Булгаков" });
                });

            modelBuilder.Entity("LibraryApp.Models.Genre", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Genres");
                    b.HasData(
                        new { Id = 1, Description = "Крупное прозаическое произведение", Name = "Роман" },
                        new { Id = 2, Description = "Произведения классической литературы", Name = "Классика" },
                        new { Id = 3, Description = "Научная фантастика и фэнтези", Name = "Фантастика" });
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("AuthorId").HasColumnType("INTEGER");
                    b.Property<int>("GenreId").HasColumnType("INTEGER");
                    b.Property<string>("ISBN").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                    b.Property<int>("PublishYear").HasColumnType("INTEGER");
                    b.Property<int>("QuantityInStock").HasDefaultValue(0).HasColumnType("INTEGER");
                    b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("AuthorId");
                    b.HasIndex("GenreId");
                    b.ToTable("Books");
                    b.HasData(
                        new { Id = 1, AuthorId = 1, GenreId = 1, ISBN = "978-5-17-090000-1", PublishYear = 1869, QuantityInStock = 5, Title = "Война и мир" },
                        new { Id = 2, AuthorId = 1, GenreId = 1, ISBN = "978-5-17-090000-2", PublishYear = 1877, QuantityInStock = 3, Title = "Анна Каренина" },
                        new { Id = 3, AuthorId = 2, GenreId = 2, ISBN = "978-5-17-090000-3", PublishYear = 1866, QuantityInStock = 7, Title = "Преступление и наказание" },
                        new { Id = 4, AuthorId = 3, GenreId = 2, ISBN = "978-5-17-090000-4", PublishYear = 1967, QuantityInStock = 4, Title = "Мастер и Маргарита" });
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.HasOne("LibraryApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("LibraryApp.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
